[package]
name         = "ethereum-proto-compiler"
version      = "0.1.0"
edition      = "2021"

[dependencies]
prost-build = "0.11"
tempdir     = "0.3.7"
walkdir     = "2.3"
argh        = "0.1.3"
tonic-build = "0.8"
